dist: focal
language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    update: true
    packages:
      - build-essential
      - cmake
      - libboost-all-dev

script:
  # Skip formatting check because clang-format in Travis is too old.
  #   # Ensure code is already properly formatted.
  #   - diff -u <(cat include/* test/*) <(clang-format include/* test/*)
  # Ensure no committed file is larger than the file size limit.
  - python3 scripts/ensure_git_has_no_large_files.py
  - mkdir build && cd build || exit
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - clang-tidy ../src/*
  - cmake --build .
  - ./test --report_level=detailed
